services:
  mw_public:
    environment:
      MW_SERVER: https://localhost

  mw_private:
    environment:
      MW_SERVER: https://localhost:8443

  caddy_public:
    environment:
      PUBLIC_HOST: localhost
    volumes:
      - ./ops/caddy/Caddyfile.public.local:/etc/caddy/Caddyfile:ro

  caddy_private:
    environment:
      PRIVATE_HOST: localhost
    volumes:
      - ./ops/caddy/Caddyfile.private.local:/etc/caddy/Caddyfile:ro
